---
- name: Run show running-config
  ansible.netcommon.cli_command:
    command: show running-config
  register: config_output

- name: Save config to file
  copy:
    content: "{{ config_output.stdout }}"
    dest: "{{ output_dir }}/{{ inventory_hostname }}-{{ date }}.cfg"